# Generated by Django 3.2.5 on 2021-07-26 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='НазваниеИнгридиента')),
            ],
        ),
        migrations.CreateModel(
            name='Soups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ИмяПродукта')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описаниие')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Цена')),
                ('weight', models.CharField(max_length=5, verbose_name='МассаБлюда')),
                ('calorie_content', models.CharField(max_length=255, verbose_name='КалорийностьБлюда')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ИмяПродукта')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описаниие')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Цена')),
                ('weight', models.CharField(max_length=5, verbose_name='МассаНапитка')),
                ('type', models.CharField(max_length=255, verbose_name='ТипНапитка')),
                ('calorie_content', models.CharField(max_length=255, verbose_name='КалорийностьНапитка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
